name: Build
on: ["pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: RUSTFLAGS="-D warnings" cargo build --all-features
